services:
  api:
    container_name: aurabus_api
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./docs:/app/docs
    depends_on:
      - db
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: db
      API_URL: ${API_URL}
      API_USER: ${API_USER}
      API_PASSWORD: ${API_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      REFRESH_SECRET: ${REFRESH_SECRET}
      GOOGLE_AUTH_CLIENT_ID: ${GOOGLE_AUTH_CLIENT_ID}
      PREDICTION_URL: ${PREDICTION_URL}
      MONGO_URI: ${MONGO_URI}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}

  db:
    container_name: aurabus_mongo_db
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
  
  ai-service:
    build: ./ai-service
    container_name: aurabus-ai
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/app
    env_file:
      - .env
    depends_on:
      - db


  redis:
    container_name: aurabus_redis
    image: redis:alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  mongo-data:
  redis-data:
